export const data = [
  {
    name: 'Photo 1',
    url: '/images/photo_1.jpg',
    description: 'Photo 1 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 2',
    url: '/images/photo_2.jpg',
    description: 'Photo 2 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 3',
    url: '/images/photo_3.png',
    description: 'Photo 3 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 4',
    url: '/images/photo_4.jpg',
    description: 'Photo 4 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 5',
    url: '/images/photo_5.jpg',
    description: 'Photo 5 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 6',
    url: '/images/photo_6.jpg',
    description: 'Photo 6 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 7',
    url: '/images/photo_7.jpg',
    description: 'Photo 7 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 8',
    url: '/images/photo_8.jpg',
    description: 'Photo 8 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
  {
    name: 'Photo 9',
    url: '/images/photo_9.jpg',
    description: 'Photo 9 description',
    date: '2020-01-01',
    type: 'image/jpg',
  },
];
